### PR TITLE
Repair Chartkick on Heroku 

### PR DESCRIPTION
**Pull request by brittanyjspringer**
- Reordered the javascript dependencies
- Uncommented the Devise secret key 

username: 'wolfgang.truong@gmail.com'
password: 'password'

Chartkick is working on deployed version of Heroku here, after I went into console and inserted a bunch of events into this application: 

https://hidden-tundra-49673.herokuapp.com/registered_applications/10
screen shot 2017-11-06 at 8 01 49 pm

### CODE REVIEW

**Comment by wolffles** [comment]
was that all that had to be done!? wow so you just had to reorder the dependencies in application.js?
I saw we added jquery to the list of dependencies too. @wonderwoman13

**Comment by wolffles** [comment]
@wonderwoman13 just curious what makes added dependencies different than including them into our gemfile, to clarify why do we only add some of the gems names to the dependencies?

**Comment by brittanyjspringer** [comment]
@wolffles Including a JS dependency wrapped in a Ruby into our Gemfile technically does nothing to the application. It pre-loads the library into our code but does not execute it. It is application.js's job to order and compile the actual dependencies that we will use. For example: I could install the angularjs-rails and not use Angular anywhere in the app.

**Comment by wolffles** [comment]
@wonderwoman13 I see so JS based gems need to be imported then. But gems like devise don’t?

**Comment by brittanyjspringer** [comment]
@wolffles exactly! If you're good with this change, please merge.

**Comment by wolffles** [comment]
thank you britt you really do go above and beyond :D

**Pull request merged**
